In [ ]:
from google.colab import files
uploaded = files.upload()

Saving TON_1TAHUN - Data_TonCoin1 (1).csv to TON_1TAHUN - Data_TonCoin1 (1) (1).csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('TON_1TAHUN - Data_TonCoin1 (1).csv')

df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username;;;;;;;;;;;;;
0,1885024606135652376,Thu Jan 30 19:54:41 +0000 2025,1.0,@elvis_analyst As of January 30 2025 the total...,1.885054e+18,NaN,elvis_analyst,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188505404322921...,4.872744e+09,;;;;;;;;;;;;;
1,1885052205239263713,Thu Jan 30 19:47:22 +0000 2025,0.0,Toncoinは売り圧力に直面していますが、潜在的な反転シグナルが現れています。 Explo...,1.885052e+18,NaN,NaN,ja,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188505220523926...,1.608215e+18,;;;;;;;;;;;;;
2,1885049842830860641,Thu Jan 30 19:37:59 +0000 2025,1.0,Toncoin'de (TON) dikkatini çekecek sinyaller v...,1.885050e+18,NaN,NaN,tr,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504984283086...,1.703122e+18,;;;;;;;;;;;;;
3,1885049549581914414,Thu Jan 30 19:36:49 +0000 2025,0.0,gmonad! I'm reserving both toncoin.nad and ton...,1.885050e+18,NaN,NaN,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504954958191...,1.722112e+18,;;;;;;;;;;;;;
4,1885044257641169196,Thu Jan 30 19:15:48 +0000 2025,0.0,gmonad! I'm reserving both toncoin.mon and ton...,1.885044e+18,NaN,NaN,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504425764116...,1.520908e+18,;;;;;;;;;;;;;

In [ ]:
print("Jumlah baris, kolom:", df.shape)
print(df.columns.tolist())

Jumlah baris, kolom: (1202, 15)
['conversation_id_str', 'created_at', 'favorite_count', 'full_text', 'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'user_id_str', 'username;;;;;;;;;;;;;']

In [ ]:
df.columns = df.columns.str.replace(';', '', regex=False)
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['conversation_id_str', 'created_at', 'favorite_count', 'full_text', 'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'user_id_str', 'username']

In [ ]:
df = df.replace(';+', '', regex=True)

In [ ]:
df = df.replace(r'^\s*$', np.nan, regex=True)

/tmp/ipykernel_7976/2450314316.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(r'^\s*$', np.nan, regex=True)

In [ ]:
df = df[df['full_text'].astype(str).str.strip() != '']

In [ ]:
df = df.drop_duplicates(subset=['full_text'])
df = df.reset_index(drop=True)

In [ ]:
print("Ukuran data setelah cleaning:", df.shape)
df.head()

Ukuran data setelah cleaning: (1156, 15)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1885024606135652376,Thu Jan 30 19:54:41 +0000 2025,1.0,@elvis_analyst As of January 30 2025 the total...,1.885054e+18,NaN,elvis_analyst,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188505404322921...,4.872744e+09,NaN
1,1885052205239263713,Thu Jan 30 19:47:22 +0000 2025,0.0,Toncoinは売り圧力に直面していますが、潜在的な反転シグナルが現れています。 Explo...,1.885052e+18,NaN,NaN,ja,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188505220523926...,1.608215e+18,NaN
2,1885049842830860641,Thu Jan 30 19:37:59 +0000 2025,1.0,Toncoin'de (TON) dikkatini çekecek sinyaller v...,1.885050e+18,NaN,NaN,tr,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504984283086...,1.703122e+18,NaN
3,1885049549581914414,Thu Jan 30 19:36:49 +0000 2025,0.0,gmonad! I'm reserving both toncoin.nad and ton...,1.885050e+18,NaN,NaN,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504954958191...,1.722112e+18,NaN
4,1885044257641169196,Thu Jan 30 19:15:48 +0000 2025,0.0,gmonad! I'm reserving both toncoin.mon and ton...,1.885044e+18,NaN,NaN,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504425764116...,1.520908e+18,NaN

In [ ]:
!pip install deep-translator

Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)

In [ ]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [ ]:
from deep_translator import GoogleTranslator
from tqdm import tqdm

translator = GoogleTranslator(source='auto', target='id')

translated = []

for text in tqdm(df['full_text']):
    try:
        translated.append(translator.translate(str(text)))
    except:
        translated.append(text)

df['full_text_indonesia'] = translated

100%|██████████| 1156/1156 [10:19<00:00,  1.87it/s]

In [ ]:
df.to_csv('hasil_clean_translate.csv', index=False, encoding='utf-8-sig')

In [ ]:
files.download('hasil_clean_translate.csv')

In [ ]:
df.to_csv("dataset_rapi.csv", index=False, encoding="utf-8-sig", quoting=1)

In [ ]:
print(df.columns)
print(df.shape)
df.head()

Index(['conversation_id_str', 'created_at', 'favorite_count', 'full_text',
       'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location',
       'quote_count', 'reply_count', 'retweet_count', 'tweet_url',
       'user_id_str', 'username', 'full_text_indonesia'],
      dtype='object')
(1156, 16)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,full_text_indonesia
0,1885024606135652376,Thu Jan 30 19:54:41 +0000 2025,1.0,@elvis_analyst As of January 30 2025 the total...,1.885054e+18,NaN,elvis_analyst,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188505404322921...,4.872744e+09,NaN,"@elvis_analyst Pada tanggal 30 Januari 2025, t..."
1,1885052205239263713,Thu Jan 30 19:47:22 +0000 2025,0.0,Toncoinは売り圧力に直面していますが、潜在的な反転シグナルが現れています。 Explo...,1.885052e+18,NaN,NaN,ja,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188505220523926...,1.608215e+18,NaN,"Toncoin menghadapi tekanan jual, tetapi potens..."
2,1885049842830860641,Thu Jan 30 19:37:59 +0000 2025,1.0,Toncoin'de (TON) dikkatini çekecek sinyaller v...,1.885050e+18,NaN,NaN,tr,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504984283086...,1.703122e+18,NaN,Toncoin (TON) memiliki sinyal yang akan menari...
3,1885049549581914414,Thu Jan 30 19:36:49 +0000 2025,0.0,gmonad! I'm reserving both toncoin.nad and ton...,1.885050e+18,NaN,NaN,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504954958191...,1.722112e+18,NaN,bagus sekali! Saya memesan toncoin.nad dan ton...
4,1885044257641169196,Thu Jan 30 19:15:48 +0000 2025,0.0,gmonad! I'm reserving both toncoin.mon and ton...,1.885044e+18,NaN,NaN,en,NaN,0.0,0.0,0.0,https://x.com/undefined/status/188504425764116...,1.520908e+18,NaN,bagus sekali! Saya memesan toncoin.mon dan ton...

In [ ]:
from google.colab import files
files.download("dataset_toncoin_rapi.csv")